function Export-M365Report {
    <#
    .SYNOPSIS
        Exports data to CSV, HTML, JSON, or console in a standardized format.
    .DESCRIPTION
        Accepts pipeline input of PSCustomObject arrays and outputs them in the
        requested format. HTML reports use a built-in professional template.
    .PARAMETER InputData
        The data to export. Accepts pipeline input.
    .PARAMETER Format
        Output format: Console, CSV, HTML, JSON. Multiple formats can be specified.
    .PARAMETER OutputPath
        Directory for file output. Defaults to ./output.
    .PARAMETER Title
        Report title (used in HTML and as filename base).
    .PARAMETER PassThru
        If specified, also returns the data as pipeline output.
    .EXAMPLE
        Get-M365CAPolicy | Export-M365Report -Format CSV, HTML -Title 'CA Policy Audit'
    .EXAMPLE
        $data | Export-M365Report -Format Console
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, ValueFromPipeline)]
        [object[]]$InputData,

        [Parameter()]
        [ValidateSet('Console', 'CSV', 'HTML', 'JSON')]
        [string[]]$Format = @('Console'),

        [Parameter()]
        [string]$OutputPath = './output',

        [Parameter()]
        [string]$Title = 'M365 Report',

        [Parameter()]
        [switch]$PassThru
    )

    begin {
        $allData = [System.Collections.Generic.List[object]]::new()
    }

    process {
        foreach ($item in $InputData) {
            $allData.Add($item)
        }
    }

    end {
        if ($allData.Count -eq 0) {
            Write-M365Log -Message "No data to export." -Level Warning
            return
        }

        $timestamp = Get-Date -Format 'yyyy-MM-dd_HHmmss'
        $safeTitle = $Title -replace '[^\w\-]', '_'

        foreach ($fmt in $Format) {
            switch ($fmt) {
                'Console' {
                    $allData | Format-Table -AutoSize | Out-String | Write-Host
                }
                'CSV' {
                    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }
                    $csvPath = Join-Path $OutputPath "$safeTitle`_$timestamp.csv"
                    $allData | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
                    Write-M365Log -Message "CSV exported: $csvPath" -Level Info
                }
                'JSON' {
                    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }
                    $jsonPath = Join-Path $OutputPath "$safeTitle`_$timestamp.json"
                    $allData | ConvertTo-Json -Depth 10 | Set-Content -Path $jsonPath -Encoding UTF8
                    Write-M365Log -Message "JSON exported: $jsonPath" -Level Info
                }
                'HTML' {
                    if (-not (Test-Path $OutputPath)) { New-Item -Path $OutputPath -ItemType Directory -Force | Out-Null }
                    $htmlPath = Join-Path $OutputPath "$safeTitle`_$timestamp.html"

                    $css = @"
<style>
    body { font-family: 'Segoe UI', Tahoma, sans-serif; margin: 20px; background: #f5f5f5; }
    h1 { color: #0078d4; border-bottom: 2px solid #0078d4; padding-bottom: 10px; }
    .meta { color: #666; font-size: 0.9em; margin-bottom: 20px; }
    table { border-collapse: collapse; width: 100%; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.12); }
    th { background: #0078d4; color: white; padding: 12px 15px; text-align: left; }
    td { padding: 10px 15px; border-bottom: 1px solid #eee; }
    tr:hover { background: #f0f6ff; }
    .footer { margin-top: 20px; color: #999; font-size: 0.8em; }
</style>
"@
                    $tableHtml = $allData | ConvertTo-Html -Fragment
                    $html = @"
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>$Title</title>$css</head>
<body>
    <h1>$Title</h1>
    <div class="meta">Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss') | Items: $($allData.Count)</div>
    $tableHtml
    <div class="footer">Generated by M365TenantSuperpowers</div>
</body>
</html>
"@
                    $html | Set-Content -Path $htmlPath -Encoding UTF8
                    Write-M365Log -Message "HTML exported: $htmlPath" -Level Info
                }
            }
        }

        if ($PassThru) {
            return $allData
        }
    }
}
